image: gradle:alpine

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - saas-linux-large-amd64
  script:
    - gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

deploy:
  stage: deploy
  tags:
    - saas-linux-large-amd64
  script:
    - gradle publish
  only:
    - main
  when: manual
  allow_failure: false
