image: gradle:8.2-jdk17

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - ./gradlew assemble --no-daemon

deploy:
  stage: deploy
  script:
    - ./gradlew publish --no-daemon
  only:
    - main
  when: manual
  allow_failure: false
