image: gradle:8.2-jdk17

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - gradle assemble

deploy:
  stage: deploy
  script:
    - gradle publish
  only:
    - main
  when: manual
  allow_failure: false
